Maintenance = [
    {"sop_id": "SOP007", "interlock_name": "ESD Push button_Under Maintenance", "alert_category": "Safety", "equipment_name": "Esd"},
    {"sop_id": "SOP008", "interlock_name": "Rim Seal system_Under Maintenance", "alert_category": "Safety", "equipment_name": "RIMSEAL"},
    {"sop_id": "SOP009", "interlock_name": "Tank_Under Maintenance", "alert_category": "Safety", "equipment_name": ["VFT", "Radar", "ROSOV", "MOV", "RIMSEAL"]},
    {"sop_id": "SOP010", "interlock_name": "ROSOV_Under Maintenance", "alert_category": "Safety", "equipment_name": "ROSOV"},
    {"sop_id": "SOP010A", "interlock_name": "MOV_Under Maintenance", "alert_category": "Process", "equipment_name": "MOV"},
    {"sop_id": "SOP011", "interlock_name": "VFT_Under Maintenance", "alert_category": "Safety", "equipment_name": "VFT"},
    {"sop_id": "SOP012", "interlock_name": "Secondary Radar_Under Maintenance", "alert_category": "Safety", "equipment_name": "Radar"},
    {"sop_id": "SOP013", "interlock_name": "Fire engine_Under Maintenance", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP013", "interlock_name": "JockeyPump_Under Maintenance", "alert_category": "Safety", "equipment_name": "Jockey Pump"},
    {"sop_id": "SOP013", "interlock_name": "HydrantPT_Under Maintenance", "alert_category": "Safety", "equipment_name": "PT"},
    {"sop_id": "SOP014", "interlock_name": "HCD_Under Maintenance", "alert_category": "Safety", "equipment_name": "Hcd"}
]

Fault = [
    {"sop_id": "SOP004", "interlock_name": "Rim Seal system_Fault activated", "alert_category": "Safety", "equipment_name": "RIMSEAL"},
    {"sop_id": "SOP016", "interlock_name": "HCD_Fault activated", "alert_category": "Safety", "equipment_name": "Hcd"},
    {"sop_id": "SOP017", "interlock_name": "AirCompressor_Fault activated", "alert_category": "Safety", "equipment_name": "Air Compressor"},
    {"sop_id": "SOP018", "interlock_name": "ROSOV_FailtoClose", "alert_category": "Safety", "equipment_name": "ROSOV"},
    {"sop_id": "SOP019", "interlock_name": "Fire engine_ FailtoStart", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP019", "interlock_name": "Fireengine_LLOP", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP019", "interlock_name": "FireEngine_HWOT", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP019", "interlock_name": "FireEngine_Tripped", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP020", "interlock_name": "Jockeypump_ FailtoStart", "alert_category": "Safety", "equipment_name": "Jockey Pump"}
]

Normal = [
    {"sop_id": "SOP001", "interlock_name": "HHH alarm from VFT", "alert_category": "Safety", "equipment_name": "VFT"},
    {"sop_id": "SOP001", "interlock_name": "HHH alarm from Secondary Radar guage", "alert_category": "Safety", "equipment_name": "Radar"},
    {"sop_id": "SOP01A", "interlock_name": "ROSOV_Close Status", "alert_category": "Safety", "equipment_name": "ROSOV"},
    {"sop_id": "SOP01A", "interlock_name": "MOV_Close Status", "alert_category": "Process", "equipment_name": "MOV"},
    {"sop_id": "SOP002", "interlock_name": "Plant ESD activated", "alert_category": "Safety", "equipment_name": "Esd"},
    {"sop_id": "SOP02A", "interlock_name": "All ROSOVs closed", "alert_category": "Safety", "equipment_name": "Esd"},
    {"sop_id": "SOP02A", "interlock_name": "Tanks in TTL Dispatch in Dormant Mode", "alert_category": "Safety", "equipment_name": "Esd"},
    {"sop_id": "SOP02A", "interlock_name": "As Power ESD Activation in Main PMCC Panel after 120 Sec", "alert_category": "Safety", "equipment_name": "Esd"},
    {"sop_id": "SOP02A", "interlock_name": "Hooter cum strobe for ESD activated in control room", "alert_category": "Safety", "equipment_name": "Hooter"},
    {"sop_id": "SOP02A", "interlock_name": "Siren Activated", "alert_category": "Safety", "equipment_name": "Esd"},
    {"sop_id": "SOP02A", "interlock_name": "ESD Command To Process PLC", "alert_category": "Safety", "equipment_name": "Esd"},
    {"sop_id": "SOP02A", "interlock_name": "All DBBVs Closed", "alert_category": "Safety", "equipment_name": "Esd"},
    {"sop_id": "SOP02A", "interlock_name": "All Tanks in Dormant Mode", "alert_category": "Safety", "equipment_name": "Esd"},
    {"sop_id": "SOP02A", "interlock_name": "All TLF Product Pumps Stopped", "alert_category": "Safety", "equipment_name": "Esd"},
    {"sop_id": "SOP02A", "interlock_name": "TLF Gantry Permissive Power Off", "alert_category": "Safety", "equipment_name": "Esd"},

    {"sop_id": "SOP02A", "interlock_name": "Barrier Gate opened", "alert_category": "Process", "equipment_name": "Barrier Gate"},
    {"sop_id": "SOP003", "interlock_name": "Proof Test_VFT_Failed", "alert_category": "Safety", "equipment_name": "VFT"},
    {"sop_id": "SOP003", "interlock_name": "Proof Test_Secondary Radar Guage_Failed", "alert_category": "Safety", "equipment_name": "Radar"},
    {"sop_id": "SOP003", "interlock_name": "Proof Test_VFT_Success", "alert_category": "Safety", "equipment_name": "VFT"},
    {"sop_id": "SOP003", "interlock_name": "Proof Test_Secondary Radar Guage_Success", "alert_category": "Safety", "equipment_name": "Radar"},
    {"sop_id": "SOP005", "interlock_name": "HCD_20% LEL activated", "alert_category": "Safety", "equipment_name": "Hcd"},
    {"sop_id": "SOP005", "interlock_name": "HCD_40% LEL activated", "alert_category": "Safety", "equipment_name": "Hcd"},
    {"sop_id": "SOP006", "interlock_name": "Earthing Failure Alarm", "alert_category": "Process", "equipment_name": "Loading Point"},
    {"sop_id": "SOP015", "interlock_name": "Dykevalve_Activated", "alert_category": "Safety", "equipment_name": "Dyke"},
    {"sop_id": "SOP021", "interlock_name": "SafetyPLC_Communication fail", "alert_category": "Safety", "equipment_name": "Plc"},
    {"sop_id": "SOP021", "interlock_name": "UPS_Fail", "alert_category": "Process", "equipment_name": "Ups"},
    {"sop_id": "SOP021", "interlock_name": "UPS_Lowbattery", "alert_category": "Process", "equipment_name": "Ups"},
    {"sop_id": "SOP021", "interlock_name": "ProcessPLC_Communication fail", "alert_category": "Process", "equipment_name": "Plc"},
    {"sop_id": "SOP022", "interlock_name": "LRC Master Switchover required in 30 days", "alert_category": "Process", "equipment_name": "Lrc Switchover"},
    {"sop_id": "SOP023", "interlock_name": "Main Fire Engines not in REMOTE", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP023", "interlock_name": "WATER Level below Reference Volume", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP023", "interlock_name": "Two Fire Engine Running status", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP023A", "interlock_name": "Hooter Activated at control room", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP023A", "interlock_name": "All TLF Product Pumps Stopped", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP023A", "interlock_name": "TLF Header Line MOV Close", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP023A", "interlock_name": "Gantry Permissive Off", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP023A", "interlock_name": "All BCU Permissive Fail Status", "alert_category": "Gantry", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP024", "interlock_name": "Day End totaliser Mismatch", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP025", "interlock_name": "BCU Local Loading", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP025", "interlock_name": "BCU permissive fail status", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP026", "interlock_name": "BCU vs MFM totalizer mismatch alarm", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP027", "interlock_name": "K Factor Change_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP027", "interlock_name": "K Factor Change_MFM", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP027", "interlock_name": "K Factor Change Blend_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "No Flow alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "No Flow alarm Blend_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},   
    {"sop_id": "SOP028", "interlock_name": "Low Flow alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Low Flow alarm Blend_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "High Flow Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "High Flow Alarm Blend_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Unauthorized Flow Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Unauthorized Flow Alarm Blend_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Meter overrun Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Meter overrun Alarm Blend_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Blend overdose Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Blend Underdose Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Additive Overdose Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Additive Underdose Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028A", "interlock_name": "BCU Permissive Off", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028A", "interlock_name": "BCU Permissive Off_Fail", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "BCU Loading Status", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP029", "interlock_name": "Tank level change during dormant mode", "alert_category": "Process", "equipment_name": "Tank Leakage"},
    # {"sop_id": "SOP031", "interlock_name": "Min 5% Manual Cross-check records", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP032", "interlock_name": "Primary Radar Guage_H alarm", "alert_category": "Process", "equipment_name": "Primary Level"},
    {"sop_id": "SOP032", "interlock_name": "Primary Radar Guage_HH alarm", "alert_category": "Process", "equipment_name": "Primary Level"},
    {"sop_id": "SOP035", "interlock_name": "Gantry Permissive_Override", "alert_category": "Gantry", "equipment_name": "Gantry Override"},
    {"sop_id": "SOP061", "interlock_name": "Unauthorized flow_BCU", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP062", "interlock_name": "Cancel TT Reported", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP063", "interlock_name": "Manual FAN printed less than 5% of total TT loaded", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP063", "interlock_name": "Manual FAN printed more than 5% of total TT loaded", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP064", "interlock_name": "TT Overloaded", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP065", "interlock_name": "BCU K- Factor Change", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP066", "interlock_name": "Bay reassignment", "alert_category": "Gantry", "equipment_name": "BCU"},
    # {"sop_id": "SOP067", "interlock_name": "Manual Bay reasignment reported", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP068", "interlock_name": "SickTT Reported", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP069", "interlock_name": "MFM K Factor Change", "alert_category": "Gantry", "equipment_name": "BCU"},
    # {"sop_id": "SOP073", "interlock_name": "Day End Report", "alert_category": "Gantry", "equipment_name": "BCU"},
    # {"sop_id": "SOP074", "interlock_name": "TAS User access report", "alert_category": "Gantry", "equipment_name": "BCU"},
    # {"sop_id": "SOP075", "interlock_name": "Local order/Standalone Order Entryt", "alert_category": "Gantry", "equipment_name": "BCU"},
]