interlock_to_category = {
    "Process": [
        "Earthing Failure Alarm",
        "UPS fail alarm",
        "PLC fault alarm",  
        "LRC Master Switchover required in 30 days",  
        "Tank level change during dormant mode",  
        "Primary RG High Level alarm",  
        "TAS User access report",  
        "Local order/Standalone Order Entry",
    ],
    "Safety": [
        "Tank Overfill Protection",
        "Tank overfill prevention close inlet ROSOV",  
        "Tank overfill prevention close inlet MOV",  
        "Plant ESD Closure of Effect",  
        "All Tanks in Dormant Mode",  
        "All DBBVs Closed",  
        "All TLF Product Pumps Stopped",  
        "ESD Command To Process PLC",  
        "All Tanks in Dormant Mode",  
        "TLF Gantry Permissive Power Off",  
        "Barrier Gate opened",  
        "Hooter cum strobe for ESD activated in control room",  
        "Siren Activated",  
        "Tanks in TTL Dispatch in Dormant Mode",  
        "Power ESD Activation in Main PMCC Panel after 120 Sec",  
        "All ROSOVs closed",  
        "Tank Overfill Proof test Failed",  
        "Tank Overfill Proof test Updated",  
        "Tank Rim Seal fault Detection System", 
        "HCDS Audio Alarm in Control Room, Audio Alarm in Field", 
        "ESD is Under Maintenance",
        "RimSeal is Under Maintenance",  
        "Tank is Under Maintenance",
        "ROSOV is Under Maintenance",
        "VFT is Under Maintenance",
        "Radar is Under Maintenance",  
        "Fire protection asset undergoing maintenance",
        "HCD is Under Maintenance",
        "Dyke Valve Audio Alarm in Control Room, Audio Alarm in Field",
        "HCD Fault Alarm",
        "Air Compressor Fault",
        "OL ROSOV failed to close",  
        "REC ROSOV failed to close",  
        "Tank overfill prevention close inlet1 ROSOV",
        "Tank overfill prevention close inlet2 MOV",
        "Tank overfill prevention close inlet1 MOV", 
        "IL1 ROSOV failed to close",  
        "IL2 ROSOV failed to close",  
        "Tank overfill prevention close inlet2 ROSOV",  
        "Fire engine fail to start",  
        "Jockey pump fail to start",  
        "Firefighting system parameter",  
        "TLF Gantry Permissive Power Off",  
        "All TLF Product Pumps Stopped",  
        "TLF Header Line MOV Close",
    ],
    "Gantry": [
        "BCU Totalizer Mismatch with last day Totalizer",  
        "BCU Local Loading"  
        "BCU Totalizer Mismatch with MFM Totalizer",  
        "K - Factor Changed",  
        "Blend Underdose Alarm",  
        "No Flow",  
        "Additive Overdose Alarm",  
        "Meter overrun Alarm",  
        "Additive Underdose Alarm",  
        "Unauthorized Flow Alarm",  
        "High Flow Alarm",  
        "Blend overdose Alarm",  
        "Low Flow",  
        "BCU Loading Status", 
        "Manual - bay assignment of more 5% of total TT loaded, Manual FAN printed more 5% of total TT loaded",  
        "Min 5% Manual Cross-check records",  
        "Sick TT_ truck",  
        "Cancel TT_ truck",  
        "Gantry Permissive override",  
        "Unauthorized flow",  
        "Bay reasignment",  
        "TT Overloaded",  
        "Day End Report",
    ],
    "FE&Jockey": [
        "Fire engine in local",
    ],
    "WaterLevl": [
        "Water volume is below threshold",
    ],
    "FoamQty": [
        "Foam volume is below threshold",
    ],
    "PT": [
        "Hydrant Line PT is below 7 Kg",
    ],
    "Check Scale alerts": [
        "Check Scale Rejection"
    ],
    "Valve leak alerts": [
        "Valve Leakage Rejection"
    ],
    "Valve leak alerts": [
        "O-Ring Leakage Rejection"
    ]
}