from enum import Enum


class InterlockTemplateMapping(str, Enum):
    INTERLOCK_ALERT = "interlock_alert_activation.html"
    INTERLOCK_ALERT_CLOSURE = "interlock_alert_closure.html"
    INTERLOCK_ESCALATE = "interlock_escalate.html"
    INTERLOCK_EXCEPTION = "interlock_exception.html"
    BLOCKING_ALERT = "vts_truck_blocking.html"
    VTS_REJECTED = "vts_truck_unblocking_rejected.html"
    VTS_JUSTIFIED = "vts_truck_blocked_justification.html"
    VTS_RESOLVED = "vts_truck_unblocked.html"
    VTS_SENDITBACK = "vts_interlock_senditback.html"
    VTS_ACCEPT = "vts_blocking_accepted.html"
    BLACKLISTED = "vts_truck_blacklisted.html"
    SOD_SHOW_CAUSE_NOTICE = "sod_show_case_template.html"
    BLOCK_OUTLET = "block_outlet.html"
    UNBLOCK_OUTLET = "unblock_outlet.html"
    VTS_DEVICE_EXPIRY = "vts_device_expiry.html"
    LOSS_OF_COMMUNICATION_ALERT = "loss_of_communication_alert.html"
    LOSS_OF_COMMUNICATION_RESOLVED = "loss_of_communication_resolved.html"


class TemplateMapping(str, Enum):
    ACTIVE = "INTERLOCK_ALERT"
    NOTIFY = "INTERLOCK_ALERT"
    REJECT = "INTERLOCK_ALERT"
    ESCALATION = "INTERLOCK_ESCALATE"
    EXCEPTION = "INTERLOCK_EXCEPTION"
    BLOCK = ""
    UNBLOCK = ""
    JUSTIFIED="INTERLOCK_ALERT"
    RESOLVED="INTERLOCK_ALERT_CLOSURE"
    BLOCKING="BLOCKING_ALERT"
    VTSREJECTED="VTS_REJECTED"
    VTSJUSTIFIED="VTS_JUSTIFIED"
    VTSRESOLVED="VTS_RESOLVED"
    SENDITBACK="VTS_SENDITBACK"
    ACCEPT="VTS_ACCEPT"
    BLACKLISTED="BLACKLISTED"
    SODSHOWCAUSENOTICE="SOD_SHOW_CAUSE_NOTICE"
    BLOCKOUTLET="BLOCK_OUTLET"
    UNBLOCKOUTLET="UNBLOCK_OUTLET"
    VTS_DEVICE_EXPIRY="VTS_DEVICE_EXPIRY" 