sales_zone_map = {
    "WZL": "WZ",
    "NWL": "NWZ",
    "EZL": "EZ",
    "NZL": "NZ",
    "NCL": "NCZ",
    "SZL": "SZ",
    "SCL": "SCZ",
    "SZ": "SZ",
    "EZ": "EZ",
    "SCZ": "SCZ",
    "NWZ": "NWZ",
    "NZ": "NZ",
    "NCZ": "NCZ",
    "WZ": "WZ",
    "NFZ": "NFZ",
    "NWF": "NWZ",
    "NCR": "NCZ",
    "SCR": "SCZ",
    "NWR": "NWZ",
    "SC": "SCZ",
    "NW": "NWZ",
    "COR": "COR",
    "ECZ": "ECZ",
    "SWZ": "SWZ",
    "CEN": "CEN"
}