export interface PlantPerformanceData {
  plantName: string;
  sbu: string;
  zone: string;
  capacity: string;
  generationToday: string;
  efficiency: string;
  gridStatus: string;
  status: string;
}

export const plantPerformanceData: PlantPerformanceData[] = [
  {
    plantName: 'LPG Plant Alpha-1',
    sbu: 'LPG',
    zone: 'North',
    capacity: '5.2 MW',
    generationToday: '12.5 MWh',
    efficiency: '48%',
    gridStatus: 'Offline',
    status: 'Critical',
  },
  {
    plantName: 'Pipeline Depot B',
    sbu: 'Pipeline',
    zone: 'West',
    capacity: '2.1 MW',
    generationToday: '8.2 MWh',
    efficiency: '88%',
    gridStatus: 'Online',
    status: 'Warning',
  },
  {
    plantName: 'SOD Terminal Gamma',
    sbu: 'SOD',
    zone: 'South',
    capacity: '3.5 MW',
    generationToday: '15.3 MWh',
    efficiency: '95%',
    gridStatus: 'Online',
    status: 'Normal',
  },
  {
    plantName: 'LPG Plant Beta-2',
    sbu: 'LPG',
    zone: 'East',
    capacity: '4.8 MW',
    generationToday: '11.2 MWh',
    efficiency: '92%',
    gridStatus: 'Online',
    status: 'Normal',
  },
  {
    plantName: 'Solar Farm Delta-1',
    sbu: 'Solar',
    zone: 'North',
    capacity: '6.5 MW',
    generationToday: '18.7 MWh',
    efficiency: '96%',
    gridStatus: 'Online',
    status: 'Normal',
  },
  {
    plantName: 'Wind Energy Station Epsilon',
    sbu: 'Wind',
    zone: 'West',
    capacity: '4.2 MW',
    generationToday: '9.8 MWh',
    efficiency: '75%',
    gridStatus: 'Online',
    status: 'Warning',
  },
  {
    plantName: 'Hydro Plant Zeta',
    sbu: 'Hydro',
    zone: 'South',
    capacity: '8.3 MW',
    generationToday: '22.1 MWh',
    efficiency: '98%',
    gridStatus: 'Online',
    status: 'Normal',
  },
  {
    plantName: 'LPG Plant Theta-3',
    sbu: 'LPG',
    zone: 'East',
    capacity: '3.9 MW',
    generationToday: '10.5 MWh',
    efficiency: '42%',
    gridStatus: 'Offline',
    status: 'Critical',
  },
  {
    plantName: 'Pipeline Depot Iota',
    sbu: 'Pipeline',
    zone: 'North',
    capacity: '5.7 MW',
    generationToday: '13.2 MWh',
    efficiency: '85%',
    gridStatus: 'Online',
    status: 'Warning',
  },
  {
    plantName: 'SOD Terminal Kappa',
    sbu: 'SOD',
    zone: 'West',
    capacity: '7.1 MW',
    generationToday: '19.4 MWh',
    efficiency: '91%',
    gridStatus: 'Online',
    status: 'Normal',
  },
  {
    plantName: 'Solar Farm Lambda',
    sbu: 'Solar',
    zone: 'South',
    capacity: '4.5 MW',
    generationToday: '12.8 MWh',
    efficiency: '88%',
    gridStatus: 'Online',
    status: 'Normal',
  },
  {
    plantName: 'Wind Energy Station Mu',
    sbu: 'Wind',
    zone: 'East',
    capacity: '3.8 MW',
    generationToday: '8.9 MWh',
    efficiency: '65%',
    gridStatus: 'Online',
    status: 'Warning',
  },
  {
    plantName: 'Hydro Plant Nu',
    sbu: 'Hydro',
    zone: 'North',
    capacity: '9.2 MW',
    generationToday: '24.6 MWh',
    efficiency: '97%',
    gridStatus: 'Online',
    status: 'Normal',
  },
  {
    plantName: 'LPG Plant Xi-4',
    sbu: 'LPG',
    zone: 'West',
    capacity: '2.9 MW',
    generationToday: '7.3 MWh',
    efficiency: '38%',
    gridStatus: 'Offline',
    status: 'Critical',
  },
  {
    plantName: 'Pipeline Depot Omicron',
    sbu: 'Pipeline',
    zone: 'South',
    capacity: '6.3 MW',
    generationToday: '16.8 MWh',
    efficiency: '82%',
    gridStatus: 'Online',
    status: 'Warning',
  },
  {
    plantName: 'SOD Terminal Pi',
    sbu: 'SOD',
    zone: 'East',
    capacity: '5.4 MW',
    generationToday: '14.2 MWh',
    efficiency: '93%',
    gridStatus: 'Online',
    status: 'Normal',
  },
  {
    plantName: 'Solar Farm Rho',
    sbu: 'Solar',
    zone: 'North',
    capacity: '7.8 MW',
    generationToday: '21.5 MWh',
    efficiency: '94%',
    gridStatus: 'Online',
    status: 'Normal',
  },
  {
    plantName: 'Wind Energy Station Sigma',
    sbu: 'Wind',
    zone: 'West',
    capacity: '4.6 MW',
    generationToday: '11.1 MWh',
    efficiency: '72%',
    gridStatus: 'Online',
    status: 'Warning',
  },
  {
    plantName: 'Hydro Plant Tau',
    sbu: 'Hydro',
    zone: 'South',
    capacity: '8.7 MW',
    generationToday: '23.3 MWh',
    efficiency: '99%',
    gridStatus: 'Online',
    status: 'Normal',
  },
  {
    plantName: 'LPG Plant Upsilon-5',
    sbu: 'LPG',
    zone: 'East',
    capacity: '3.2 MW',
    generationToday: '8.6 MWh',
    efficiency: '45%',
    gridStatus: 'Offline',
    status: 'Critical',
  },
];

