export const initialEdges = [
  {
    id: "elrca-safety-group",
    source: "lrca",
    target: "safety-group",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "elrcb-safety-group",
    source: "lrcb",
    target: "safety-group",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "elrca-gantry_bcu",
    source: "lrca",
    target: "gantry_bcu",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "elrcb-gantry_bcu",
    source: "lrcb",
    target: "gantry_bcu",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "elrca-mfm",
    source: "lrca",
    target: "mfm",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "elrcb-mfm",
    source: "lrcb",
    target: "mfm",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "elrca-process-group",
    source: "lrca",
    target: "process-group",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "elrcb-process-group",
    source: "lrcb",
    target: "process-group",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "eprocess-group-primary_radar",
    source: "process-group",
    target: "primary_radar",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "eprocess-group-mov",
    source: "process-group",
    target: "mov",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "eprocess-group-pumps",
    source: "process-group",
    target: "pumps",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "eprocess-group-barrier_gate",
    source: "process-group",
    target: "barrier_gate",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },

  {
    id: "esafety-group-rosov",
    source: "safety-group",
    target: "rosov",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "esafety-group-vft",
    source: "safety-group",
    target: "vft",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },

  {
    id: "esafety-group-secondary_radar",
    source: "safety-group",
    target: "secondary_radar",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },

  {
    id: "esafety-group-pt_hydrant",
    source: "safety-group",
    target: "pt_hydrant",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },

  {
    id: "esafety-group-hooter",
    source: "safety-group",
    target: "hooter",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },

  {
    id: "esafety-group-esd",
    source: "safety-group",
    target: "esd",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },

  {
    id: "esafety-group-fire_engine",
    source: "safety-group",
    target: "fire_engine",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },

  {
    id: "esafety-group-hcd",
    source: "safety-group",
    target: "hcd",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },

  {
    id: "esafety-group-dyke",
    source: "safety-group",
    target: "dyke",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },

  {
    id: "esafety-group-jockey_pump",
    source: "safety-group",
    target: "jockey_pump",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },

  {
    id: "esafety-group-air_compressor",
    source: "safety-group",
    target: "air_compressor",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "eups-safety-group",
    source: "ups",
    target: "safety-group",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
  {
    id: "eups-process-group",
    source: "ups",
    target: "process-group",
    type: "smoothstep",
    animated: true,
    style: { stroke: "#000", strokeWidth: 5, strokeDasharray: "5 5" },
  },
];
