# SSL Configuration
ssl_certificate     /etc/nginx/certs/certificate.crt;
ssl_certificate_key /etc/nginx/certs/privatekey.key;
ssl_protocols       TLSv1.2 TLSv1.3;
server_tokens off;
more_clear_headers Server;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;

# Max content size to allow
client_max_body_size 100M;

# For Security/VAPT
# Refer policy should not add if we are using third party urls
add_header Referrer-Policy "strict-origin-when-cross-origin";
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header Access-Control-Allow-Origin $http_origin;
# add_header Content-Security-Policy "Default-src 'self' data:; Style-src 'unsafe-inline' 'self'; img-src 'self' data: https://va.hpcl.co.in;" always;
add_header Content-Security-Policy "Default-src 'self'; Style-src 'unsafe-inline' 'self'; img-src 'self' data: https://va.hpcl.co.in data:; font-src 'self' data:;" always;

add_header X-Permitted-Cross-Domain-Policies master-only;
add_header Cache-Control "no-cache, no-store, must-revalidate";
